apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: service-a-peerauth
  namespace: default
spec:
  selector:
    matchLabels:
      app: service-a
  mtls:
    mode: PERMISSIVE

