apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-policy-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-policy-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "list", "patch", "get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch", "list"]
- apiGroups: ["mesh.example.com"]
  resources: ["trafficpolicies"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]   # <<---- ADD THIS BLOCK
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-policy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traffic-policy-role
subjects:
- kind: ServiceAccount
  name: traffic-policy-controller
  namespace: default

