apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: service-b-peerauth
  namespace: default
spec:
  selector:
    matchLabels:
      app: service-b
  mtls:
    mode: PERMISSIVE

