apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mtlspeers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                mode:
                  type: string
  scope: Namespaced
  names:
    plural: mtlspeers
    singular: mtlspeer
    kind: MtlsPeer
    shortNames:
    - mp

