apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trafficpolicies.mesh.example.com
spec:
  group: mesh.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        type: string
                        enum:
                          - allow
                          - deny
                          - rate-limit
                      condition:
                        type: string
  scope: Namespaced
  names:
    plural: trafficpolicies
    singular: trafficpolicy
    kind: TrafficPolicy
    shortNames:
    - tp

