# crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podautoscalers.autoscaler.example
spec:
  group: autoscaler.example
  names:
    kind: PodAutoScaler
    plural: podautoscalers
    singular: podautoscaler
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                cpuThresholdHigh:
                  type: integer
                cpuThresholdLow:
                  type: integer
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer

