
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: d2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  selector:
    app: nginx2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

